### YamlMime:YamlDocument
documentType: LandingData
title: Documentação do Azure Container Service com o Kubernetes
metadata:
  document_id: null
  title: 'Documentação do Azure Container Service com o Kubernetes - Tutoriais, Referência da API | Microsoft Docs'
  meta.description: 'Azure Container Service allows you to quickly deploy a production ready Kubernetes cluster. Learn how to use Azure Container Service in concert with Kubernetes with these quickstarts, tutorials, and samples.'
  services: container-service
  author: carolz
  manager: carolz
  ms.service: container-service
  ms.tgt_pltfrm: na
  ms.devlang: na
  ms.topic: landing-page
  ms.date: 07-21-2017
  ms.author: carolz
abstract:
  description: 'O Azure Container Service permite-lhe implementar rapidamente um cluster do Kubernetes pronto para produção. Saiba como utilizar o Azure Container Service em conjunto com o Kubernetes com estes guias de introdução, tutoriais e amostras.'
sections:
  - title: Inícios rápidos de cinco minutos
    items:
      - type: paragraph
        text: 'Saiba como implementar clusters Kubernetes com o Azure Container Service:'
      - type: list
        style: icon48
        items:
          - image:
              src: 'https://docs.microsoft.com/media/logos/logo_linux.svg'
            text: Criar um cluster do Kubernetes
            href: /azure/container-service/kubernetes/container-service-kubernetes-walkthrough
  - title: Tutoriais Passo-a-Passo
    items:
      - type: paragraph
        text: 'Saiba como implementar, gerir e atualizar aplicações num cluster do Kubernetes do Azure Container Service.'
      - type: list
        style: ordered
        items:
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-prepare-app">Criar imagens de contentor a partir de uma aplicação</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-prepare-acr">Carregar imagens de contentor para o Azure Container Registry</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-deploy-cluster">Implementar um cluster do Kubernetes no Azure Container Service</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-deploy-application">Executar as imagens de contentor no Kubernetes</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-scale">Dimensionar uma aplicação e a infraestrutura do Kubernetes</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-app-update">Atualizar uma aplicação em execução no Kubernetes</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-monitor">Monitorizar o Kubernetes com o OMS</a>
  - title: Amostras
    items:
      - type: list
        style: unordered
        className: spaced noBullet
        items:
          - html: <a href="/azure/container-service/cli-samples">CLI do Azure</a>
  - title: Referência
    items:
      - type: list
        style: cards
        className: cardsD
        items:
          - title: Linha de Comandos
            html: <p><a href="/cli/azure/acs">CLI do Azure</a></p>
          - title: REST
            html: <p><a href="/rest/api/compute/containerservices">API REST</a></p>